package civitas.crypto.signedciphertext.tests;

import java.util.Base64;

import civitas.common.CommonUtil;
import civitas.crypto.ciphertext.tests.ElGamalCiphertextTestData;
import civitas.crypto.signedciphertext.ElGamalSignedCiphertext;
import civitas.util.CivitasBigInteger;
import civitas.util.CivitasBigIntegerFactory;

public interface ElGamalSignedCiphertextTestData extends ElGamalCiphertextTestData {

	String EL_GAMAL_SIGNED_CIPHERTEXT_C_BASE64 = "dHKDA9V8OEUx/Z2A7TLdgbG7OdIZTbg860iANjgFJMI=";
	CivitasBigInteger EL_GAMAL_SIGNED_CIPHERTEXT_HASH1 = BIGINT_G.modPow(RANDOMS_0, BIGINT_P);
	CivitasBigInteger EL_GAMAL_SIGNED_CIPHERTEXT_A = BIGINT_G.modPow(FACTOR_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_SIGNED_CIPHERTEXT_B =
			MESSAGE_VOTE_CAPABILITY_SHARE_ENCODED.modMultiply(PUBKEY_E.modPow(FACTOR_E, BIGINT_P), BIGINT_P);
	CivitasBigInteger EL_GAMAL_SIGNED_CIPHERTEXT_C =
			CivitasBigIntegerFactory.obtain(Base64.getDecoder().decode(EL_GAMAL_SIGNED_CIPHERTEXT_C_BASE64));
	CivitasBigInteger EL_GAMAL_SIGNED_CIPHERTEXT_D =
			RANDOMS_0.modAdd(EL_GAMAL_SIGNED_CIPHERTEXT_C.modMultiply(FACTOR_E, BIGINT_Q), BIGINT_Q);

	ElGamalSignedCiphertext EL_GAMAL_SIGNED_CIPHERTEXT = new ElGamalSignedCiphertext(
			EL_GAMAL_SIGNED_CIPHERTEXT_A, EL_GAMAL_SIGNED_CIPHERTEXT_B,
			EL_GAMAL_SIGNED_CIPHERTEXT_C, EL_GAMAL_SIGNED_CIPHERTEXT_D);
	CivitasBigInteger HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV =
			CommonUtil.asBigint("dHKDA9V8OEUx/Z2A7TLdgbG7OdIZTbg860iANjgFJMI=");
	CivitasBigInteger HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR =
			CommonUtil.asBigint("AKw6iOIfDUU0OHK6D2nQ/e40bKkVIrYwO+kUZJuwSWYt");

	CivitasBigInteger RANDOMS_0_PLUS_HASH_MUL_FACTOR = RANDOMS_0.modAdd(
			HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV.modMultiply(
					FACTOR_E, BIGINT_Q),
			BIGINT_Q);

	CivitasBigInteger RANDOMS_0_PLUS_HASH_MUL_FACTOR_NOENV = RANDOMS_0.modAdd(
			HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR.modMultiply(FACTOR_E, BIGINT_Q),
			BIGINT_Q);

	CivitasBigInteger G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV = BIGINT_G.modPow(
					RANDOMS_0_PLUS_HASH_MUL_FACTOR.mod(BIGINT_Q), BIGINT_P)
			.modMultiply(
					CIPHERTEXT_E_A.modPow(
							HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV.modNegate(
									BIGINT_Q),
							BIGINT_P),
					BIGINT_P);

	CivitasBigInteger G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV_BAD = BIGINT_G.modPow(
					RANDOMS_0_PLUS_HASH_MUL_FACTOR.mod(BIGINT_Q), BIGINT_P)
			.modMultiply(CIPHERTEXT_E_A.modPow(BIGINT_C.modNegate(BIGINT_Q), BIGINT_P), BIGINT_P);
	CivitasBigInteger G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_BAD = BIGINT_G.modPow(
					RANDOMS_0_PLUS_HASH_MUL_FACTOR_NOENV.mod(BIGINT_Q), BIGINT_P)
			.modMultiply(CIPHERTEXT_E_A.modPow(BIGINT_C.modNegate(BIGINT_Q), BIGINT_P), BIGINT_P);

	CivitasBigInteger G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR = BIGINT_G.modPow(
					RANDOMS_0_PLUS_HASH_MUL_FACTOR.mod(BIGINT_Q), BIGINT_P)
			.modMultiply(
					CIPHERTEXT_E_A.modPow(
							HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR.modNegate(BIGINT_Q),
							BIGINT_P),
					BIGINT_P);

	ElGamalSignedCiphertext SIGNED_CIPHERTEXT_OF_MESSAGE_WITH_FACTOR_RANDOM0_ADDITIONALENV =
			new ElGamalSignedCiphertext(
					CIPHERTEXT_E_A,
					CIPHERTEXT_E_B,
					HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR_ADDITIONALENV,
					RANDOMS_0_PLUS_HASH_MUL_FACTOR);

	ElGamalSignedCiphertext SIGNED_CIPHERTEXT_OF_MESSAGE_WITH_FACTOR_RANDOM0_ADDITIONALENV_BAD =
			new ElGamalSignedCiphertext(CIPHERTEXT_E_A, CIPHERTEXT_E_B, BIGINT_C, RANDOMS_0_PLUS_HASH_MUL_FACTOR);

	ElGamalSignedCiphertext SIGNED_CIPHERTEXT_OF_MESSAGE_WITH_FACTOR_RANDOM0 = new ElGamalSignedCiphertext(
			CIPHERTEXT_E_A,
			CIPHERTEXT_E_B,
			HASH_OF_G_POW_RANDOMS0_G_EXP_FACTOR_MESSAGE_MUL_PUBKEY_POW_FACTOR,
			RANDOMS_0_PLUS_HASH_MUL_FACTOR_NOENV);

	ElGamalSignedCiphertext SIGNED_CIPHERTEXT_OF_MESSAGE_WITH_FACTOR_RANDOM0_BAD =
			new ElGamalSignedCiphertext(CIPHERTEXT_E_A, CIPHERTEXT_E_B, BIGINT_C, RANDOMS_0_PLUS_HASH_MUL_FACTOR_NOENV);
}
