package civitas.crypto.concrete;

import civitas.common.Util;
import civitas.util.CivitasBigInteger;

public interface ElGamalProofDiscLogEqualityCTestData
		extends ElGamalParametersCTestData, BasicValuesTestData {

	public static final ElGamalReencryptFactorC REENCRYPT_FACTOR_RANDOMS_1 = new ElGamalReencryptFactorC(
			RANDOMS_1);
	public static final CivitasBigInteger PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR = GENERATOR_OTHER
			.modPow(REENCRYPT_FACTOR_RANDOMS_1.r, BIGINT_P);
	String PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR_BASE64 = Util
			.fromBigInt(PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR);
	public static final CivitasBigInteger PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR_POW_A = PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR
			.modPow(BIGINT_A, BIGINT_P);
	public static final String PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR_POW_A_BASE64 = Util
			.fromBigInt(PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR_POW_A);

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_V_BASE64 = "LD3Xb9CI+9aPuf4txqHYiDyOL4PcF2RAzcOndY4FeWBOlj7K44vApsoEVdM7NORPAyWFgD5ZukhP101ovmQuCzS0cvlrRdhDCEnItsZTIgJihXa6AO9iYj5Xt9WfIxnTK6awTfsqQG6Mikhxdgj0qtJcJGzr9pVECZYWtjl5j8zwVnglqnes8NEAPCqaFRiHlYI2yepb6qSHjJAcRNZJ6vaMAtg3og9f1tdNGE332/2uglZ+zI+lOnyvnJCTMriC4qFPsgdfZop24YvnJQTEdpx1KdcTA5sBFxiYxRWtBDUS8eRKLv2l6G7aIOdrWBmvIjFcMqBmyOiT9bDl4DwZE+Y/UKV7y3mx2HIJ/ofI1SBbAOE11s3cCoeXboi2LbOQ7BE4L15owPKtZliKhBFwhqJ3cz3L4gZUQ2EqV7nc6S4aC7YYIoVRzqA8juLClg51k7KTZYrcmWw8DR0fH7iNJBPmGqnCqYnFuSzch+0SmJGAQCA9RwEiYSafncM5IO1S";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_W_BASE64 = "bYNRiWtK8H8jaehxs1S+YKemiiip2QacwnwcQqKHsPBE1KzsZEBVquxOmPa8FGLV4hUd5okpWdQImk9ntTNCKC3q9yq7Grr7xUAoS3QMwQ0N4B18eENIjUO9eACm6IcPf+3tK87fp7h35ZQHA0XJJNxSVRz97ARYjIcXg9x/jBPbsHqXDfkrAhfneWqBajxu5+8kygrp3pS/DVZI9cB/WUvfS5idySJ/YLQKzcXxlqSPeRdHN3vNyE/DaJ2MGHqiEJE1qo2p3kc5R31gceixV9WQFQn7PJ9RrrZ1Isvar+zpsStQdH92Kr0KU+3d/fxuJnpxToA0J8J/mpIat7uj9jugW5qCJ1ERRarjcbjtpi1jZKaDB28704VzudfgAQq5U3O+0MsWRgJ6MClQvWWwXiPK9xAmm7u3b6tvUBemAQhvAbpYgoCmyuq8UiDo7H7EiAB27OcpfrjbprUlEkux7DapIW+X6V85qqZX/myyjnO7kS9l2ju3JYUGOA2A0IlM";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_A_BASE64 = "Rv8nzR8sePqrFAUcQpTG1wp/ppOvVKX2Gc4C3rpPbpQu5si1p9EvgjNSn3eTwwzMeoz0KpuZn1ccs0pMaFqAUW8WcUz80Hh+w4FMvM7yinmZAAzO+W8eEvQ4dNAR1aopWAbDcJDEj6+sq/3Esz9LZr5OEfbeUlzy8u3fIsfqhIsTyMnV3bfMC2sbv7i1Bz7udFa2uBCm6eHgqobZmVWxLFw5jloe1oJapQxjx8lHcatzTmdox0VrChF61On7k0gdWMTL1hffiMnNFaCWT5A3lv+YJ378Xc5cpN0eY5BXnSJ804qdXshg5+fRTukbizmQj6l9nuKp/HwmHL6IbUO651EoYEc1KDNfogQH2Lt4QhQ4RpO5qDjjqOviPLj/+0uR8/FFVzyNSxJUv2K/+UIZ//4JwlEAtczX/eD+bIkodzFOF6U5REo0o3Vn8+b7rgbhvyasLTuHj8v/xApSNd+Xxm1fPg7F/dBfUu+7LBdC7XqEYj59PctCU3a/JeEdqaVA";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_B_BASE64 = "cZP5shp3SOALmUwEY6Zj6crdGhQzIB7fkbIS9sLCUzI4tZDlzROdfCm6EHz1sd5ekqrVwzRfwKBBuOrGeoujtfXJ7e1U5nxgCzcXTJAwhIsuM0KVyvgPV8krRzzRf1/hP7hSwzh4eWCpWKmzfREuoJBe0RKnrv+jBi0U46tSRRgz9qg5x3K92fTEtiCWQnLb5JlA+VWbJNxsdGm99o2t4wcmRdK2ZmOYFPdxmpCLLV5eCWCHCO/rZxBtWwhKScvwhjjbcnSlefNb4MXjEwk3j97Uulz7rt35KKDUMmcxDjpwHbkoAl7lbhtXNPgaPIrcIM60DDdclM8cwXz1ItvUbOzlprPLgjyskGj4g0Kmz+K6v/NfFRCKM2FA9QKlMSlpGWGsQt68+EYAvgTNAdoiSNdoDP+YBY1B6ITg384VcHOIzBhORrLupPR9iPUoIvU0GelBNciOhXjnFUjuWTSpsoCj47N9GBq9GGsYXpTBuXTMI/9wIsqUPT+sjOrvQERl";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_C_BASE64 = "B28X8Z/5mPsYbQ1KMeM9pw1+kCL641p4IKzGdYRBKcs=";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_R_BASE64 = "fjFmifAPnCcEJRCG8Xu51T0ATrAJ+IxsaIoJGh8iLts=";
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_V = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_V_BASE64);
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_W = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_W_BASE64);
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_A = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_A_BASE64);
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_B = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_B_BASE64);
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_C = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_C_BASE64);
	public static final CivitasBigInteger EL_GAMAL_PROOF_DISC_LOG_EQUALITY_R = Util
			.asBigint(EL_GAMAL_PROOF_DISC_LOG_EQUALITY_R_BASE64);
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_XML = "<egPrfKnwDscLog><g1>"
			+ PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR_BASE64 + "</g1><g2>"
			+ BIGINT_G_BASE64 + "</g2><v>" + EL_GAMAL_PROOF_DISC_LOG_EQUALITY_V_BASE64
			+ "</v><w>" + EL_GAMAL_PROOF_DISC_LOG_EQUALITY_W_BASE64 + "</w><a>"
			+ EL_GAMAL_PROOF_DISC_LOG_EQUALITY_A_BASE64 + "</a><b>"
			+ EL_GAMAL_PROOF_DISC_LOG_EQUALITY_B_BASE64 + "</b><c>"
			+ EL_GAMAL_PROOF_DISC_LOG_EQUALITY_C_BASE64 + "</c><r>"
			+ EL_GAMAL_PROOF_DISC_LOG_EQUALITY_R_BASE64 + "</r></egPrfKnwDscLog>";
	public static final ElGamalProofDiscLogEqualityC EL_GAMAL_PROOF_DISC_LOG_EQUALITY = new ElGamalProofDiscLogEqualityC(
			PUBKEY_VALUE_OTHER_GENERATOR_RANDOM1_FACTOR, BIGINT_G,
			EL_GAMAL_PROOF_DISC_LOG_EQUALITY_A, EL_GAMAL_PROOF_DISC_LOG_EQUALITY_V,
			EL_GAMAL_PROOF_DISC_LOG_EQUALITY_W, EL_GAMAL_PROOF_DISC_LOG_EQUALITY_B,
			EL_GAMAL_PROOF_DISC_LOG_EQUALITY_C, EL_GAMAL_PROOF_DISC_LOG_EQUALITY_R);

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_BAD_W_XML = "<egPrfKnwDscLog><g1>"
			+ BIGINT_G_BASE64 + "</g1><g2>" + GENERATOR_OTHER_BASE64
			+ "</g2><v>d9AUMsYNk5ZQ+ZbjfZz7UgyjyklNj+gwz/MjRyrlLjWVnK/ghtTfAv4qIisD407XCf8Whv+2Us9JcXDuh2ptfNIWJibe2RX6ivjBH/1VyaOylbJ4BGfLFcyNiPxrjAPzJ1LdlSHjkXII3VrmyD72hF4gnzrKExGmDyi9tffhcfZoZvTgxzeVdjvR2PKK/k4Ug0zqjyQyKJUnDP3RB1q+31/RB3S6E+LMyr9ToxQWRS7IymyzsQXV6smygtzZKE+PBU+gIJjxQ6ALt3/VImxazonOPhO9VCSoNfTVwAVvK5FdXvS6utK0GHTnHx0U/D/4W880NWwbB7DIxdvpYnjpK45MxVvoGelhUqMMPOjMM+7cn3o6QLATVB1QHbo7w7yH2P+Q0tcr9itruIjI2sajoZkEMG5n6DJunwqHVZx38BScxUlmKb8rKW8+AhOC3BXBe5biUDReBdRtpSkOFi5as1mWxsIH2EvGAG2bPUtIZuCn0phLG37M32XyhDiOEehm</v><w>"
			+ BIGINT_C_BASE64
			+ "</w><a>bYNRiWtK8H8jaehxs1S+YKemiiip2QacwnwcQqKHsPBE1KzsZEBVquxOmPa8FGLV4hUd5okpWdQImk9ntTNCKC3q9yq7Grr7xUAoS3QMwQ0N4B18eENIjUO9eACm6IcPf+3tK87fp7h35ZQHA0XJJNxSVRz97ARYjIcXg9x/jBPbsHqXDfkrAhfneWqBajxu5+8kygrp3pS/DVZI9cB/WUvfS5idySJ/YLQKzcXxlqSPeRdHN3vNyE/DaJ2MGHqiEJE1qo2p3kc5R31gceixV9WQFQn7PJ9RrrZ1Isvar+zpsStQdH92Kr0KU+3d/fxuJnpxToA0J8J/mpIat7uj9jugW5qCJ1ERRarjcbjtpi1jZKaDB28704VzudfgAQq5U3O+0MsWRgJ6MClQvWWwXiPK9xAmm7u3b6tvUBemAQhvAbpYgoCmyuq8UiDo7H7EiAB27OcpfrjbprUlEkux7DapIW+X6V85qqZX/myyjnO7kS9l2ju3JYUGOA2A0IlM</a><b>WQpOdIhgR+KH1I9+lYcl22z9xVYgc4qILfBCtAiRNgzVXPyEmmNnxAsWoLfc8BVuby4myfUf0n6Ck/fbFb7KmFqgTwUFcKCyCNYntd8REmg8Ls2MyS2Ra0iN42YIY8wXWsRrG7b40x27w5Wa4sCQTnERwsreiYAp6d1Ipy7CI3VYkOofeEx/hA/JGyhMbXJBnu0NbRTfxJGEdFzQViWxnsMG7U0jc8U+dzmLnEr2Fqad8v6d+fo76/TKql5Tlf/TjkRXOccyytFDv3uR00xTye3DhfxQSEepg8q+oZEktYsKaAZtFI0XA3o2iLIEU3bIRY7osIwRF3NG/tsJe7lY64C/XlnjYrjZXPJU8lFVa+ia/qf/pBG9iJrxob7bNNusK4T8JzUpa59xj3l+GYTP6xA2+DsIFoE7qQxlzBJ+iZrm4qPDXrX1epXqdtqZxDJ7SMkC7RezNXE4f99zUuyzwjawoloVqwqxdjcTqcA1i58i32PbQ9Nk4GyaMJK8xpPV</b><c>KuVSbUZLCxsOwKXOW+l7eHlxJp4/u8Asi/Y5kRPXnSQ=</c><r>V2q34Ktm0U62EhHJWMVvQUxNec+E79FBqqFyNn5O8K0=</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_NULL_XML = "<egPrfKnwDscLog><g1></g1><g2></g2><v></v><w></w><a></a><b></b><c></c><r></r></egPrfKnwDscLog>";
	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_NAIVE_XML = "<egPrfKnwDscLog><g1>"
			+ BIGINT_G_BASE64 + "</g1><g2>" + GENERATOR_OTHER_BASE64 + "</g2><v>"
			+ BIGINT_B_BASE64 + "</v><w>" + BIGINT_C_BASE64 + "</w><a>"
			+ BIGINT_A_BASE64 + "</a><b>" + BIGINT_D_BASE64 + "</b><c>"
			+ BIGINT_A_ENCRYPTED_SAFE_BASE64 + "</c><r>" + G_OTHER_BASE64
			+ "</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_D_BASE64 = "TS3s5NYNMm250l/s0cCsBcFIB/H58hj1YtAVP+WBOTCURAvqpa5uE6joHVRmfzg9eY/uvY04YSJ7uqBEDHRykHnya1IExGd2adQXiP6RmPPPrbyGo1019LEtP19mWiQUlXfiYTmDAr9XSSK56yHt2gXPsQy0jYsI3qIvGKUHsJsYRTk1jpeY3nXqYPXzdJCg1GIgk05wHz7KbHQdgbfMjh/HiGfS5b7+G1w4jc2BEqGxGqE5/fT9M75/TJ9V2HvfvP0PHiEqdcHpo0x/aeGkXU1zvlUw2gU6pORF3qaejYL04b293ErSQRo5D1ggZFtYHpfc0hR1Mzy31QRwTHGt3cwunQxjlxqzgHdE48Zg27mZM2vVpAIhTxVQJAdIvt82URPjJixPg5fHhpI/N1AGsqkuFAc3dGQmnKI4i8ztBZW9VUkt9d14UAnpF47AJkmQSyGLkCng3JNKQQ6P8jjJz5CnC37iulVDPrTaXKubPFQf1AlqEAhj//GGYOfifbxy";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_E_BASE64 = "SD7Z3Dapm/Dh2U1Rr5mOtxnwKiKMChA9pv6Wlf14bmuAIoc6UGFgwfiCgBzMGKuanTxj/+3dnz3QTOYgRNFgp7BiqPauzsVX/g+0mpb9nd+6e+HpbEdr7+DxCLqoZJYAjlrvKCIeV+jnX+Zh188iWUOH2jSGKWNp/EcjRxYVJZkZCCyo1/+bbXELJkG419AJTUlF5M4Oc6UQOGEd47rm4KD8GG4qSkJdmBhuQEwDrVyWV3MgbVUp6Ylsv5BhefF5rENyOgrLR4SABWj8G2ro/Vvo6qlX8xdbs8FUSwa27iEHTDWlUevHSTtX8hKC1EmBUwF6lcXtbYlVGUZ7L+52jLGygkcgTPNOLhWoTSYqYG/+PS4LQz1lHQcIW24VIfMekzRpgYPQI8UCNiA5P4VCdtbXMF/nAlJZpCNpC3d3IJW9lJhzmNVYTSymPvTlZDzWYYw+SWK+yN5BM9dITQW2uhXcMwKy72D7JmxvgtgqUpEZFwwvW2hEVMzfzkJpbwAj";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_ZI_BASE64 = "eaUSELMHNaE=";

	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_D = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_D_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_E = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_E_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_ZI = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_ZI_BASE64);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_V_BASE64 = "MSXYn+/AgD1p9v4NWcEoowO4CzjHVh8VbE4wYBifZAWIP+Xdo52+r5djtqyWDWbuzXsI9i0Neneez49SCv0ygeJiR7MmdAmG4J3ORqA6xTD4UDx55PcPPMpc6uTuc4dvGqjdNbKilXA4jWXLqZenbMZqTRi3aEADvLoZxwaf8oivyUZEAVL+N31+8wcduU7iicBMQpg8GquJuvrKpQrJ/NegEKKbOAC/hUhu5DjtG9OOwNn0YNIYXrPMfVvIynqbncXQDlshfYwbgW7w7MbJLwEhyCvqSYPJp4N2PEZxdmxq7+Aa3/qLgRvJFvyjWCUG0Iz6gK487CLqLsO15gWOPVIPUi4CKhEjmx4vjwpZfw1I56iVyiUjHN3B2QElgh3AyprVYyPLT2+07HwEUbMOjWnZKR2hS/s73t2lLfFUKNw+H4c4aw73tRF06yVv81l6yEtKYiDNzcpr4pCaoUOIz9Nt24A7NMxryfAxIMgr0CfQZIs3WXTXs22OrUJ1w5cD";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_W_BASE64 = "CKgUB0V3mSOMAkJpqgfgqu/b/2+w78IjffAFEnc+TQ7fyHNFvXzBQAW0oWQKUzPZBN7BdTaz3qAN60/TZ2YhRDsKnYGKhXhuB0WZyy8gBxXCs3TGWFu3YtHJvbGe1/5MERVJgxCcgyasctZYHKpdvH0u8+hmRREMQfd6jjmSI9Zqjdcroih7i0z1eYkcU2HJUI7IoR5ifusqz3gBUiGV6pFu6FpruYfKxYYYfEG9N82CNmQQagsZJlT9/aWzOjUrTexfOOA+IxROWf8GjwAI1dzY/bpa49lRmJoFbmPgNan9rFKtn7CtCKR/rhU8VO0zPijYtl7WdkVDXd1ZfJ8uAz4wG97+1h/9x9tJJPtL3MVBJakiKiam/Nz15BNyKoP/tG1VCMYWV/KChCspQcZEt72n58m66nizw9FFApMipMBXg/FTAZDsqEte8nfqfbIxRO9ifkD367ktsdOWrzcngvbl951WIiWAoGIlJhXg0yOkfWJhQq8ALURac+j6VLFW";

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_A_BASE64 = "HRQj9cNai1KqjGFOHT0QdtwiAinSyghrJV+g6W/MRR4G0aVIe8yYtNsN/X3uQ88desZa/WCmZXHzUbLgaf5R+ug07BNhlvfFt1TmHPR5/0fNrPTP8TD6rHmBZ5yEjC7YLiK4JJNRwj8iAOkGndC0+bPBf8MSDLRe4kgLI0Im4RjyPMw4O1r/EeN97A1cUviZRenlsV3LXLiCJK/a12QZfmQOjIeMIPW3JKQdv42oWljbbxwKxfs/7nXxv4UT5g/7EgtBLd9U1eMG+yZal3t+CslDFchiNS4/un3+DhCJovzvWWka9/NOl3ATPAs6ZlHWTVODNlIN0EJNrOq3FBmSIbCqYWHKbYxxYUIUE8eFsZN0Kz6Yu3oynMv9r8ItsuKF0NXNibqJ3Ti7WMsf2wUMMupLQT2IJ1aZ4RGp7VjpIkMzFfxslPDqHBoNM1Wp3yFBymKKCixdQh5rcO52Fimzinf/XIbce1GOCky5Zz+XiC06bYaODchF9HgHlbMYocJL";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_B_BASE64 = "TGwfVFr1U21RV+fHAtJ9pauTd3BP8SxMvAgUIMZFu2TMwdOkDqZ04IHiJQNyrUxueEcFPzAwdbQLVm4tqOH28vB4MQpEYMaXLgYLvMzPlCVlVaImYIfNXLTdJJQRd/Edc6eqxupZH2yLxNkgZL36l5oU3bD5oBxERLf4IpwCYK9DSuV2qRdUQuT44dvjJFwo/wyjWgGaFvTsU4fNy8atDGlzzyb+MewuCkEoxUwQ+mXKdxOe0GI3f8nzn67bdKzwblwQ/URiDpGMQBtPVBdY5YWD/+psDYOYFIz+1unZh95XAfpuNW3843Ucp/CsaXzLOpXw73Y8rg+Ib9CrUVmchYl0hXDxd5Jl+QdYhf9FXJisQad9U2qfuRTRGggBAx2TiDyUrkjwZwPEZ5voal9PrhcQtFrt34v0b/RY13OKqVXzx9sKl6wtUFMnSyTuZ6aBNRlAQ/kq82nC3lvmdmds/92d4wf0x4z5nA6bCmO5mrojPWgDFZ3eDSsvdL6vN8F+";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_C_BASE64 = "eMTafDb0CrD+Fph+xYiCMOivcobRRe38g8Qn+LS+1MI=";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_R_BASE64 = "Jcf6BA40ls0h0hF0CXGani+SCCX/SigdO7Z1ywr423A=";

	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_A = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_A_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_B = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_B_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_C = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_C_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_R = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_R_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_V = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_V_BASE64);
	public static final CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_W = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_W_BASE64);

	ElGamalProofDiscLogEqualityC EL_GAMAL_DISC_LOG_EQUALITY_PROOF = new ElGamalProofDiscLogEqualityC(
			EL_GAMAL_DISC_LOG_EQUALITY_D, EL_GAMAL_DISC_LOG_EQUALITY_E,
			EL_GAMAL_DISC_LOG_EQUALITY_A, EL_GAMAL_DISC_LOG_EQUALITY_V,
			EL_GAMAL_DISC_LOG_EQUALITY_W, EL_GAMAL_DISC_LOG_EQUALITY_B,
			EL_GAMAL_DISC_LOG_EQUALITY_C, EL_GAMAL_DISC_LOG_EQUALITY_R);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_PROOF_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_D_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_E_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_R_BASE64 + "</r></egPrfKnwDscLog>";

}
