package civitas.crypto.concrete;

import civitas.common.Util;
import civitas.util.CivitasBigInteger;

public interface ElGamalProofDiscLogEqualityCTestData
		extends ElGamalCiphertextCTestData {

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_BAD_W_XML = "<egPrfKnwDscLog><g1>"
			+ BIGINT_G_BASE64 + "</g1><g2>" + GENERATOR_OTHER_BASE64
			+ "</g2><v>d9AUMsYNk5ZQ+ZbjfZz7UgyjyklNj+gwz/MjRyrlLjWVnK/ghtTfAv4qIisD407XCf8Whv+2Us9JcXDuh2ptfNIWJibe2RX6ivjBH/1VyaOylbJ4BGfLFcyNiPxrjAPzJ1LdlSHjkXII3VrmyD72hF4gnzrKExGmDyi9tffhcfZoZvTgxzeVdjvR2PKK/k4Ug0zqjyQyKJUnDP3RB1q+31/RB3S6E+LMyr9ToxQWRS7IymyzsQXV6smygtzZKE+PBU+gIJjxQ6ALt3/VImxazonOPhO9VCSoNfTVwAVvK5FdXvS6utK0GHTnHx0U/D/4W880NWwbB7DIxdvpYnjpK45MxVvoGelhUqMMPOjMM+7cn3o6QLATVB1QHbo7w7yH2P+Q0tcr9itruIjI2sajoZkEMG5n6DJunwqHVZx38BScxUlmKb8rKW8+AhOC3BXBe5biUDReBdRtpSkOFi5as1mWxsIH2EvGAG2bPUtIZuCn0phLG37M32XyhDiOEehm</v><w>"
			+ BIGINT_C_BASE64
			+ "</w><a>bYNRiWtK8H8jaehxs1S+YKemiiip2QacwnwcQqKHsPBE1KzsZEBVquxOmPa8FGLV4hUd5okpWdQImk9ntTNCKC3q9yq7Grr7xUAoS3QMwQ0N4B18eENIjUO9eACm6IcPf+3tK87fp7h35ZQHA0XJJNxSVRz97ARYjIcXg9x/jBPbsHqXDfkrAhfneWqBajxu5+8kygrp3pS/DVZI9cB/WUvfS5idySJ/YLQKzcXxlqSPeRdHN3vNyE/DaJ2MGHqiEJE1qo2p3kc5R31gceixV9WQFQn7PJ9RrrZ1Isvar+zpsStQdH92Kr0KU+3d/fxuJnpxToA0J8J/mpIat7uj9jugW5qCJ1ERRarjcbjtpi1jZKaDB28704VzudfgAQq5U3O+0MsWRgJ6MClQvWWwXiPK9xAmm7u3b6tvUBemAQhvAbpYgoCmyuq8UiDo7H7EiAB27OcpfrjbprUlEkux7DapIW+X6V85qqZX/myyjnO7kS9l2ju3JYUGOA2A0IlM</a><b>WQpOdIhgR+KH1I9+lYcl22z9xVYgc4qILfBCtAiRNgzVXPyEmmNnxAsWoLfc8BVuby4myfUf0n6Ck/fbFb7KmFqgTwUFcKCyCNYntd8REmg8Ls2MyS2Ra0iN42YIY8wXWsRrG7b40x27w5Wa4sCQTnERwsreiYAp6d1Ipy7CI3VYkOofeEx/hA/JGyhMbXJBnu0NbRTfxJGEdFzQViWxnsMG7U0jc8U+dzmLnEr2Fqad8v6d+fo76/TKql5Tlf/TjkRXOccyytFDv3uR00xTye3DhfxQSEepg8q+oZEktYsKaAZtFI0XA3o2iLIEU3bIRY7osIwRF3NG/tsJe7lY64C/XlnjYrjZXPJU8lFVa+ia/qf/pBG9iJrxob7bNNusK4T8JzUpa59xj3l+GYTP6xA2+DsIFoE7qQxlzBJ+iZrm4qPDXrX1epXqdtqZxDJ7SMkC7RezNXE4f99zUuyzwjawoloVqwqxdjcTqcA1i58i32PbQ9Nk4GyaMJK8xpPV</b><c>KuVSbUZLCxsOwKXOW+l7eHlxJp4/u8Asi/Y5kRPXnSQ=</c><r>V2q34Ktm0U62EhHJWMVvQUxNec+E79FBqqFyNn5O8K0=</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_NULL_XML = "<egPrfKnwDscLog><g1></g1><g2></g2><v></v><w></w><a></a><b></b><c></c><r></r></egPrfKnwDscLog>";

	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1 = CIPHERTEXT_E_A
			.modDivide(CIPHERTEXT_EPRIME_A, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2 = CIPHERTEXT_E_B
			.modDivide(CIPHERTEXT_EPRIME_B, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1
			.modPow(RANDOMS_0, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2
			.modPow(RANDOMS_0, BIGINT_P);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 = "AIm6aE5Q/X4ya4j3tjffpAIv6omtGzqwN5+HmeJJerGy";
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R = RANDOMS_0
			.modAdd(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C.modMultiply(
					ElGamalPrivateKeyCTestData.PRIVKEY_E, BIGINT_Q), BIGINT_Q);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R);

	ElGamalProofDiscLogEqualityC EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT = new ElGamalProofDiscLogEqualityC(
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R);

	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1 = CIPHERTEXT_E_A;
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2 = BIGINT_G;
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1
			.modPow(RANDOMS_0, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2
			.modPow(RANDOMS_0, BIGINT_P);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64 = "BR5zAZxvPyywQ6VQ0lew/Ro6h8eC41arC8Vzk8w5RzI=";
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R = RANDOMS_0
			.modAdd(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C.modMultiply(
					ElGamalPrivateKeyCTestData.PRIVKEY_E, BIGINT_Q), BIGINT_Q);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);

	ElGamalProofDiscLogEqualityC EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE = new ElGamalProofDiscLogEqualityC(
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_PROOF_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64
			+ "</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_PROOF_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R_BASE64
			+ "</r></egPrfKnwDscLog>";

}
