package civitas.crypto.proofdisclog;

import java.util.List;

import civitas.common.Util;
import civitas.crypto.ciphertext.ElGamalCiphertextTestData;
import civitas.crypto.privatekey.ElGamalPrivateKeyTestData;
import civitas.util.CivitasBigInteger;

public interface ElGamalProofDiscLogEqualityTestData
		extends ElGamalCiphertextTestData {

	public static final String EL_GAMAL_PROOF_DISC_LOG_EQUALITY_NULL_XML = "<egPrfKnwDscLog><g1></g1><g2></g2><v></v><w></w><a></a><b></b><c></c><r></r></egPrfKnwDscLog>";

	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1 = CIPHERTEXT_E_A
			.modDivide(CIPHERTEXT_EPRIME_A, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2 = CIPHERTEXT_E_B
			.modDivide(CIPHERTEXT_EPRIME_B, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1
			.modPow(RANDOMS_0, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2
			.modPow(RANDOMS_0, BIGINT_P);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 = "AIm6aE5Q/X4ya4j3tjffpAIv6omtGzqwN5+HmeJJerGy";
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R = RANDOMS_0
			.modAdd(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C.modMultiply(
					ElGamalPrivateKeyTestData.PRIVKEY_E, BIGINT_Q), BIGINT_Q);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R);

	ElGamalProofDiscLogEquality EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT = new ElGamalProofDiscLogEquality(
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R);
	List<CivitasBigInteger> EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_FOR_HASH = List
			.of(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V,
					EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W,
					EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A,
					EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B);

	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1 = CIPHERTEXT_E_A;
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2 = BIGINT_G;
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2
			.modPow(PRIVKEY_E, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1
			.modPow(RANDOMS_0, BIGINT_P);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B = EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2
			.modPow(RANDOMS_0, BIGINT_P);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64 = "BR5zAZxvPyywQ6VQ0lew/Ro6h8eC41arC8Vzk8w5RzI=";
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C = Util
			.asBigint(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64);
	CivitasBigInteger EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R = RANDOMS_0
			.modAdd(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C.modMultiply(
					ElGamalPrivateKeyTestData.PRIVKEY_E, BIGINT_Q), BIGINT_Q);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);

	ElGamalProofDiscLogEquality EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE = new ElGamalProofDiscLogEquality(
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);

	ElGamalProofDiscLogEquality EL_GAMAL_DISC_LOG_EQUALITY_BAD_G1 = new ElGamalProofDiscLogEquality(
			BIGINT_A, EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);

	ElGamalProofDiscLogEquality EL_GAMAL_DISC_LOG_EQUALITY_BAD_W = new ElGamalProofDiscLogEquality(
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V, BIGINT_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C,
			EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_PROOF_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64
			+ "</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_BAD_W_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G1_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 + "</v><w>"
			+ BIGINT_A_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64
			+ "</r></egPrfKnwDscLog>";

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_BAD_G1_XML = "<egPrfKnwDscLog><g1>"
			+ BIGINT_A_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECOMMITMENT_R_BASE64
			+ "</r></egPrfKnwDscLog>";
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A);
	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B_BASE64 = Util
			.fromBigInt(EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B);

	public static final String EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_PROOF_XML = "<egPrfKnwDscLog><g1>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G1_BASE64 + "</g1><g2>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_G2_BASE64 + "</g2><v>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_V_BASE64 + "</v><w>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_W_BASE64 + "</w><a>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_A_BASE64 + "</a><b>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_B_BASE64 + "</b><c>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_C_BASE64 + "</c><r>"
			+ EL_GAMAL_DISC_LOG_EQUALITY_FOR_DECRIPTIONSHARE_R_BASE64
			+ "</r></egPrfKnwDscLog>";

}
