#!/bin/bash
set -xe
if [ -f lib/server.jks ]
then
	exit 0
fi
mkdir -p lib
keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias supervisor -dname CN=supervisor
keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias registrar -dname CN=registrar
keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias bbs -dname CN=bbs
keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias regteller -dname CN=regteller
keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias tabteller -dname CN=tabteller

for i in 1 2 3 4
do
	keytool -keystore lib/server.jks -storepass test12345 -genkeypair -keyalg RSA -alias user$i -dname CN=user$i
done

